# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UNCsOQlPZDKRkCDPhvhkMe1Y95ZNcOyO
"""

import pandas as pd

data=pd.read_csv(r"/content/batch 3 dataset-ai financial market realistic synthesis.csv")

import pandas as pd
import streamlit as st
import plotly.express as px

# Page config
st.set_page_config(page_title="AI Financial Dashboard", layout="wide")

# Load dataset
@st.cache_data
def load_data():
    df = pd.read_csv("batch 3 dataset-ai financial market realistic synthesis.csv")
    df["Date"] = pd.to_datetime(df["Date"])
    return df

df = load_data()

# Title
st.title("📊 AI Financial Market Dashboard")

# Sidebar filters
st.sidebar.header("Filter Data")

companies = st.sidebar.multiselect(
    "Select Company",
    options=df["Company"].unique(),
    default=df["Company"].unique()
)

date_range = st.sidebar.date_input(
    "Select Date Range",
    [df["Date"].min(), df["Date"].max()]
)

# Filter data
filtered_df = df[
    (df["Company"].isin(companies)) &
    (df["Date"] >= pd.to_datetime(date_range[0])) &
    (df["Date"] <= pd.to_datetime(date_range[1]))
]

# KPIs
col1, col2, col3 = st.columns(3)

col1.metric("Total R&D Spending", f"{filtered_df['R&D_Spending_USD_Mn'].sum():,.2f} Mn USD")
col2.metric("Total AI Revenue", f"{filtered_df['AI_Revenue_USD_Mn'].sum():,.2f} Mn USD")
col3.metric("Avg Growth %", f"{filtered_df['AI_Revenue_Growth_%'].mean():.2f}%")

st.markdown("---")

# Revenue trend
fig1 = px.line(
    filtered_df,
    x="Date",
    y="AI_Revenue_USD_Mn",
    color="Company",
    title="AI Revenue Over Time"
)
st.plotly_chart(fig1, use_container_width=True)

# R&D vs Revenue
fig2 = px.scatter(
    filtered_df,
    x="R&D_Spending_USD_Mn",
    y="AI_Revenue_USD_Mn",
    color="Company",
    size=abs(filtered_df["AI_Revenue_Growth_%"]),
    title="R&D Spending vs AI Revenue"
)
st.plotly_chart(fig2, use_container_width=True)

# Stock Impact
fig3 = px.bar(
    filtered_df,
    x="Company",
    y="Stock_Impact_%",
    color="Company",
    title="Stock Impact by Company"
)
st.plotly_chart(fig3, use_container_width=True)

# Event analysis
event_df = filtered_df.dropna(subset=["Event"])

if not event_df.empty:
    fig4 = px.histogram(
        event_df,
        x="Event",
        color="Company",
        title="Events Distribution"
    )
    st.plotly_chart(fig4, use_container_width=True)
else:
    st.info("No event data available for selected filters")